name: dev_feed
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  async: ^2.11.0
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  http: ^1.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  realm: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.10
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
