// Mocks generated by Mockito 5.4.4 from annotations
// in dev_feed/test/feed/viewmodel/posts_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dev_feed/feed/viewmodel/post_item_view_model.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

import 'posts_view_model_test.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ItemsLoader].
///
/// See the documentation for Mockito's code generation for more information.
class MockItemsLoader extends _i1.Mock implements _i2.ItemsLoader {
  @override
  _i3.Future<List<_i4.PostItemViewModel>> load() => (super.noSuchMethod(
        Invocation.method(
          #load,
          [],
        ),
        returnValue: _i3.Future<List<_i4.PostItemViewModel>>.value(
            <_i4.PostItemViewModel>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.PostItemViewModel>>.value(
                <_i4.PostItemViewModel>[]),
      ) as _i3.Future<List<_i4.PostItemViewModel>>);
}
