// Mocks generated by Mockito 5.4.4 from annotations
// in dev_feed/test/feed/cache/local_post_loader_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dev_feed/feed/cache/post_store.dart' as _i2;
import 'package:dev_feed/feed/model/model.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PostStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostStore extends _i1.Mock implements _i2.PostStore {
  @override
  _i3.Future<void> deleteCachedPosts() => (super.noSuchMethod(
        Invocation.method(
          #deleteCachedPosts,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> insert(List<_i4.Post>? posts) => (super.noSuchMethod(
        Invocation.method(
          #insert,
          [posts],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Post>> retrieve() => (super.noSuchMethod(
        Invocation.method(
          #retrieve,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Post>>.value(<_i4.Post>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.Post>>.value(<_i4.Post>[]),
      ) as _i3.Future<List<_i4.Post>>);
}
