// Mocks generated by Mockito 5.4.4 from annotations
// in dev_feed/test/feed/feed_ui_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i7;

import 'package:async/async.dart' as _i2;
import 'package:dev_feed/async_image/model/image_data_loader.dart' as _i6;
import 'package:dev_feed/feed/model/model.dart' as _i3;
import 'package:dev_feed/feed/model/post.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

import 'feed_ui_integration_test.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCancelableOperation_0<T> extends _i1.SmartFake
    implements _i2.CancelableOperation<T> {
  _FakeCancelableOperation_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PostLoader].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostLoader extends _i1.Mock implements _i3.PostLoader {
  @override
  _i4.Future<List<_i5.Post>> load() => (super.noSuchMethod(
        Invocation.method(
          #load,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Post>>.value(<_i5.Post>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.Post>>.value(<_i5.Post>[]),
      ) as _i4.Future<List<_i5.Post>>);
}

/// A class which mocks [ImageDataLoader].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageDataLoader extends _i1.Mock implements _i6.ImageDataLoader {
  @override
  _i2.CancelableOperation<_i7.Uint8List> load(Uri? url) => (super.noSuchMethod(
        Invocation.method(
          #load,
          [url],
        ),
        returnValue: _FakeCancelableOperation_0<_i7.Uint8List>(
          this,
          Invocation.method(
            #load,
            [url],
          ),
        ),
        returnValueForMissingStub: _FakeCancelableOperation_0<_i7.Uint8List>(
          this,
          Invocation.method(
            #load,
            [url],
          ),
        ),
      ) as _i2.CancelableOperation<_i7.Uint8List>);
}

/// A class which mocks [PostSelectionHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostSelectionHandler extends _i1.Mock
    implements _i8.PostSelectionHandler {
  @override
  void onSelected(int? id) => super.noSuchMethod(
        Invocation.method(
          #onSelected,
          [id],
        ),
        returnValueForMissingStub: null,
      );
}
