name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4.1.7

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - run: flutter --version

      - name: Setup Melos
        uses: bluefireteam/melos-action@v3
        
      - name: Install lcov
        run: sudo apt-get install lcov

      - name: Run tests with coverage
        run: melos test:with-lcov-coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          files: coverage_report/cleaned_combined_lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}

