name: CI to run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4.1.7

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - run: flutter --version

      - name: Install lcov
        run: sudo apt-get install lcov

      - name: Setup dependencies
        run: flutter pub get

      - name: Setup Realm
        run: dart run realm install

      - name: Run tests
        run: flutter test --coverage

      - name: Coverage
        run: |
          lcov --remove coverage/lcov.info '*.realm.dart' '*.g.dart' '*.freezed.dart' -o coverage/lcov.info
          echo "Filter out coverage for generated codes."
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          files: coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}

