name: CI to run tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4.1.7

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - run: flutter --version

      - name: Setup dependencies
        run: flutter pub get

      - name: Setup Realm
        run: dart run realm install

      - name: Run tests
        run: flutter test --coverage

      - name: Coverage Report
        run: |
          lcov --remove coverage/lcov.info '*.realm.dart' '*.g.dart' '*.freezed.dart' -o coverage/lcov.info
          echo "Filter out coverage for generated codes."
          genhtml coverage/lcov.info -o coverage/html
          echo "Coverage Report generated"
      
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4.3.3
        with:
          name: coverage-report
          path: coverage

